apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-erick
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql-erick
  template:
    metadata:
      labels:
        app: graphql-erick
    spec:
      containers:
      - image: okteto.dev/graphql-erick:latest
        name: graphql-erick
        #envFrom:
        #- configMapRef:
        #    name: erick-config
        livenessProbe:
          httpGet:
            path: /ht/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: graphql-erick
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "graphql-erick"
    port: 8080
  selector:
    app: graphql-erick
